language: node_js
before_install: sudo apt-get install libcairo2-dev libjpeg8-dev libpango1.0-dev libgif-dev build-essential g++
node_js:
  - 0.8
  - "0.10"
branches:
  only:
    - master
notifications:
  email:
    - rod@vagg.org
